### PR TITLE
145 enterable gate refactor

### PR DESCRIPTION
**Pull request by MrJackey**
## Summary
Fixes 145
Split up Gate script into Gate and EnterableGate.

### CODE REVIEW

**Review by smeas — DISMISSED** [review]
Cool!
Just make sure to connect the exit gates in the scenes back up to their emitters before merging. They have lost their references because of the script change.

**Comment by smeas** [comment]
These events seems like they are internal to the gate and should be hooked up from code?
image

**Review by Addehman — COMMENTED** [review]
Looking good to me! Think we just need to add those references that are missing for the gates to be connected with for example the buttons!

**Review by smeas — APPROVED** [review]
🚢

**Review by Addehman — APPROVED** [review]
Looking great!

**Pull request merged**
