### PR TITLE
Update Level 3.unity

### PR DESCRIPTION
**Pull request by Addehman**
- Moved platform for lever in extension area,
- made a pair of moving spikes more synced

### CODE REVIEW

**Review by smeas — COMMENTED** [review]
Looks good. I just have two suggestions.

Maybe disconnect this button from the exit door and make it always open to avoid disorienting the player with too much panning.
Screenshot_722

Move these spikes slightly to the left to align them better with the hole above.
Screenshot_721

**Comment by Addehman** [comment]
Oh! Great pointers! Will apply those ASAP! :D

**Comment by Addehman** [comment]
Also, I did raise the platform where the Timed Lever in the extension part is positioned, in attempt to make it more understandable that you can stay in human form there. Please have a look to see if this isn't too much hand holding..

**Review by smeas — APPROVED** [review]
Looks good!

**Review by MrJackey — APPROVED** [review]
:shipit:

**Pull request merged**
