### PR TITLE
Feature/205 implement sound effects on world items

### PR DESCRIPTION
**Pull request by Addehman**

### CODE REVIEW

**Review by MrJackey — CHANGES_REQUESTED** [review]
Whenever you play a sound you use getComponent, maybe it would be better to cache it instead?

**Comment by smeas** [comment]
> Whenever you play a sound you use getComponent, maybe it would be better to cache it instead?

Indeed. I would just use serialized fields to get references to the audio sources.

**Comment by MrJackey** [comment]
Also, the sound of the gate should probably not be played using the events they are currently hooked up to. If the camera panning is activated it delays the opening sequence but not the sound desynchronizing them.

**Comment by Addehman** [comment]
Ait, I'm on it! :) with the gate, meaning both gates I presume? and they should be played from the code instead of from events in editor?

**Review by smeas — APPROVED** [review]

**Review by MrJackey — APPROVED** [review]
+1

**Pull request merged**
