### PR TITLE
Added Human Hurt sounds

### PR DESCRIPTION
**Pull request by Addehman**

### CODE REVIEW

**Review by smeas — COMMENTED** [review]
Awesome! I think we need to replace the wolf hurt sound though. It sounds a bit silly.

**Comment by Addehman** [comment]
haha agreed, though I'm out of ideas for what to use instead.. 😅

**Review by smeas — APPROVED** [review]

**Review by smeas — APPROVED** [review]
:+1:

**Review by MrJackey — APPROVED** [review]
:shipit:

**Pull request merged**
