### PR TITLE
$121 Speech bubble system

### PR DESCRIPTION
**Pull request by smeas**
Task 121
- Added speech "bubbles"
- Fixed an issue with the `Tag` attribute

X6ZJcCaodQ
image

### CODE REVIEW

**Comment by Addehman** [comment]
Does/should the text disable controls for a moment? Also, does the text appear if we return to its trigger?

Furthermore, maybe more dots(...) in the end of the sentence to make it a bit more fitting a dead or weak person?

**Comment by smeas** [comment]
I don't think we should disable the controls. The player can read the text if they want to.
Yes, the text appears every time you enter the trigger.
Maybe, but this is just sample text.

**Comment by Addehman** [comment]
Understand better after testing, so ignore first response. However, maybe consider having a fade-out on the text when player is leaving? Juicy!

**Review by Addehman — APPROVED** [review]
Juicy!

**Review by MrJackey — APPROVED** [review]
+1

**Pull request merged**
